### PR TITLE
Implementation of parameter dependencies

### PR DESCRIPTION
**Pull request by darshanmandge**
The 'hoc' branch has implementation for parameter dependencies, where one parameter value can be made to depend on another one, created by @DrTaDa . This is used for Hallermann model.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @darshanmandge 

Can you fix the conflicts with master?

**Comment by darshanmandge** [comment]
Hi @alejoe91,
I fixed the conflicts with master but there are some tests which are failing. I will discuss with @DrTaDa about these.

Happy Easter!

**Comment by alejoe91** [comment]
Thanks Darshan! Happy Easter to you too :)

**Review by alejoe91 — APPROVED** [review]

**Comment by DrTaDa** [comment]
I added all the previous changes as well as CMA. It won't pass the tests as I had to change them, but if you agree with the changes, it can be merged.

Ps: I used black for reformatting which is why git sees so many changes.

**Comment by alejoe91** [comment]
Yep! Let's merge :)

**Pull request merged**
